from multiversx_sdk.core.address import Address

ESDT_CONTRACT_ADDRESS = Address.new_from_bech32("erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u")
METACHAIN_ID = 4294967295
MAX_UINT64 = 18446744073709551615
DEFAULT_ADDRESS_HRP = "erd"

DEFAULT_TRANSACTION_AWAITING_POLLING_TIMEOUT_IN_MILLISECONDS = 6000
DEFAULT_TRANSACTION_AWAITING_TIMEOUT_IN_MILLISECONDS = 15 * DEFAULT_TRANSACTION_AWAITING_POLLING_TIMEOUT_IN_MILLISECONDS
DEFAULT_TRANSACTION_AWAITING_PATIENCE_IN_MILLISECONDS = 3000

BASE_USER_AGENT = "multiversx-sdk"
UNKNOWN_CLIENT_NAME = "unknown"
