name: Run tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    name: Run tests on ${{ matrix.os }}, python ${{ matrix.python-version }}
    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Install other dependencies
      run: |
        wget https://github.com/ElrondNetwork/elrond-sdk-go-tools/releases/download/v1.0.0/mcl_signer_v1.0.0_ubuntu-latest.tar.gz
        tar -xf mcl_signer_v1.0.0_ubuntu-latest.tar.gz
    - name: Test with pytest
      run: |
        export MCL_SIGNER_PATH=./signer
        pytest .
