name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.11]
      max-parallel: 1  # This ensures jobs run sequentially, not concurrently

    name: Check coverage
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - name: Launch tests & generate report
        run: coverage run -m pytest -m "not mainnet"

      - name: Coverage comment
        id: coverage_comment
        if: matrix.os == 'ubuntu-latest'  # Run only on Ubuntu
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store Pull Request comment to be posted
        if: matrix.os == 'ubuntu-latest' && steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'  # Run only on Ubuntu
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
