name: CI

on:
  pull_request:
  push:
    branches: [ main, feat/* ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Check coverage
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install deps
        run: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - name: Launch tests & generate report
        run: pytest .

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          VERBOSE: true

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v2
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
          name: python-coverage-comment-action
          # If you use a different name, update COMMENT_FILENAME accordingly
          path: python-coverage-comment-action.txt
